services:
#    microservices_internal_authentication.example:
#        class: Fiser\MicroservicesInternalAuthenticationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
