services:
    guzzle_http.client:
        class: GuzzleHttp\Client

    security.token_storage:
        class: Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage

    fiser.microservices_internal_authentication.security.authenticator:
        class: Fiser\MicroservicesInternalAuthenticationBundle\Security\JWTAuthenticator
        arguments:
         - '@router'

    fiser.microservices_internal_authentication.security.user_provider:
        class: Fiser\MicroservicesInternalAuthenticationBundle\Security\JWTUserProvider
        arguments:
         - '@guzzle_http.client'
         - '@service_container'
